version: '3'

networks:
  maratona:

volumes:
  maratona-postgres-data:
    driver: local

services:
  app:
    build: .
    container_name: maratona-full-cycle
    ports:
      - 3020:3000
    networks:
      - maratona

  db:
    image: postgres:12.3
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=maratona
      - POSTGRES_DB=maratona
      - POSTGRES_USER=maratona
    volumes:
      - maratona-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - maratona
